version: "3.7"
services:
  backend:
    build: ./quix-backend/
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - MODULES
      - AUTH_COOKIE
      - AUTH_SECRET
      - AUTH_TYPE
  frontend:
    build: ./quix-frontend/
    ports:
      - "3000:3000"
    depends_on:
      - db
      - backend
    env_file:
      - .env
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_PORT
      - BACKEND_INTERNAL_URL
      - BACKEND_PUBLIC_URL
      - GOOGLE_SSO_CLIENT_ID
      - GOOGLE_SSO_SECRET
      - AUTH_COOKIE
      - AUTH_SECRET
      - AUTH_TYPE
      - APPMETRICS_PORT
      - ENABLE_APPMETRICS
      - MODULES
  presto:
    build: ./presto-server-346/
    volumes:
      - ./presto-server-346/etc:/usr/lib/presto/etc
    ports:
      - "8089:8089"
  db:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "quix"
    volumes:
      - "db_volume:/var/lib/mysql"

volumes:
  db_volume:
